---
title: "NCSUDatathon2021"
author: "Ethan Donecoff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(maps)
library(lubridate)
```


```{r import-data, echo = FALSE, include = FALSE}
incidents <- read_csv("data/Raleigh_Police_Incidents_(NIBRS).csv")
```

```{r EDA}
count <- incidents %>%
  count(crime_description) %>%
  arrange(desc(n))
```

```{r pie-chart}
# Pie chart of incidents without location
misc <- incidents %>%
  filter(latitude == 0) %>%
  mutate(crime_description = case_when
         (grepl("Non-Offenses", crime_description) ~ "Non-Offenses",
          (grepl("Sex Offense", crime_description) ~ "Sex Offenses"),
          (grepl("Missing Person|Runaway", crime_description) ~ "Missing/Runaway"),
          (grepl("Property", crime_description) ~ "Property"),
          (grepl("Misc", crime_description) ~ "Other Miscellaneous"),
          TRUE ~ "Rest"))%>%
  count(crime_description)
misc$crime_description <- factor(misc$crime_description, levels = c("Non-Offenses", "Sex Offenses", "Missing/Runaway", "Property","Other Miscellaneous", "Rest"))

ggplot(data = misc, mapping = aes(x = "", y = n, fill = crime_description)) + 
  geom_bar(stat = "identity", width = 1, color = "white") + 
  coord_polar("y", start = 0) + 
  theme_void() + 
  labs(color = "legend",
       fill = "Crime Description",
       title = "Breakdown of Incidents without Location Data")


```


```{r days-week}
# Day of week histogram
incidents$reported_dayofwk <- factor(incidents$reported_dayofwk, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
ggplot(data = incidents, mapping = aes(x = reported_dayofwk, color = reported_dayofwk)) + 
  geom_histogram(stat = "count", fill = "lightblue") + 
  labs(x = "Day of Week", 
       y = "Number of Incidents", 
       title = "Incidents by Day of Week") + 
  theme_light() + 
  theme(legend.position = "none")
```


```{r month}
#Month histogram
incidents <- incidents %>%
  mutate(month_name = case_when(reported_month == "1" ~ "January",
                                reported_month == "2" ~ "February",
                                reported_month == "3" ~ "March",
                                reported_month == "4" ~ "April",
                                reported_month == "5" ~ "May",
                                reported_month == "6" ~ "June",
                                reported_month == "7" ~ "July",
                                reported_month == "8" ~ "August",
                                reported_month == "9" ~ "September",
                                reported_month == "10" ~ "October",
                                reported_month == "11" ~ "November",
                                reported_month == "12" ~ "December"))

incidents$month_name <- factor(incidents$month_name, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))
         
ggplot(data = incidents, mapping = aes(x = month_name)) +
  geom_histogram(stat = "count", fill = "lightblue") +
  labs(x = "Month",
       y = "Number of Incidents",
       title = "Incidents by Month") +
  theme_light() +
  theme(legend.position = "none") + 
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

```{r hour}
ggplot(data = incidents, mapping = aes(x = reported_hour)) +
  geom_histogram(stat = "count", fill = "lightblue") +
  labs(x = "Hour",
       y = "Number of Incidents",
       title = "Incidents by Hour") +
  theme_light() +
  theme(legend.position = "none")
```


```{r mapping}
nc <- map_data("state") %>%
  filter(region == "north carolina")

counties <- map_data("county")
nc_county <- subset(counties, region == "north carolina")

ggplot() +
  geom_polygon( data = nc_county, aes(x=long, y=lat, group=group),
                color="black", fill = "pink" ) + 
  coord_fixed(xlim = c(-78.85, -78.5), ylim = c(35.7, 36.0)) + 
  geom_point(data = incidents, mapping = aes(x = X, y = Y, color = district)) + 
  labs(color = "District",
       title = "Map of Incidents",
       x = "Latitude", 
       y = "Longitude")
```

```{r drugs}
cats <- incidents %>%
  mutate(category = case_when(grepl("Drug", crime_description) ~ "Drugs",
                              grepl("Sex", crime_description) ~ "Sex"))

drugs <- cats %>%
  filter(category == "Drugs")

sex <- cats %>%
  filter(category == "Sex")
```

```{r cat-map}
ggplot() +
  geom_polygon( data = nc_county, aes(x=long, y=lat, group=group),
                color="black", fill = "pink" ) + 
  coord_fixed(xlim = c(-78.85, -78.5), ylim = c(35.7, 36.0)) + 
  geom_point(data = sex, mapping = aes(x = X, y = Y, color = district)) + 
  labs(color = "District",
       title = "Map of Incidents",
       x = "Latitude", 
       y = "Longitude")
```

